auto: true

#markdown: rdiscount
markdown: kramdown
#pygments: true
highlighter: rouge
paginate: 2
permalink: /:year/:month/:day/:title
blognewlist: 5

title: -10
production_url: http://hushi55.github.io
url: http://hushi55.github.io
feed: /atom.xml
feed_blogs_count: 8
author_info: <a href="http://hushi55.github.io/">-10</a>

watermark: ?watermark/2/text/LTEwJ3MgYmxvZw==/fontsize/500/font/Y291cmllciBuZXc=/fill/IzZEOThENA==