auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: -10
url: http://hushi55.github.io/
feed: /atom.xml
author_info: <a href="http://hushi55.github.io/">-10</a>

watermark: ?watermark/2/text/LTEwJ3MgYmxvZw==/fontsize/500/font/Y291cmllciBuZXc=/fill/IzZEOThENA==